### ISSUE TITLE
restobject.py could/should be nextobject.py?

### ISSUE THREAD

**Issue by tholemu** [f5-rahm/f5-ncm#2]
Not necessarily an issue, but rather a potential consideration..

Reading through common/restobject.py, it seems as though the name may have been derived from the parent iControl REST project, per comments on lines 13 and 17.

**Comment by f5-rahm** [comment]
bigrest artifact. Will clean that up next week

**Comment by f5-rahm** [comment]
actually that was a simple one. https://github.com/f5-rahm/f5-ncm/pull/3 merged.
